CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS notes (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title TEXT NOT NULL DEFAULT 'Sem título',
    review_output TEXT NOT NULL DEFAULT '',
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE notes
ADD COLUMN IF NOT EXISTS title TEXT NOT NULL DEFAULT 'Sem título';

ALTER TABLE notes
ADD COLUMN IF NOT EXISTS review_output TEXT NOT NULL DEFAULT '';

ALTER TABLE notes
ADD COLUMN IF NOT EXISTS diagnosis TEXT NOT NULL DEFAULT '';

UPDATE notes
SET title = 'Sem título'
WHERE title IS NULL OR BTRIM(title) = '';

UPDATE notes
SET review_output = ''
WHERE review_output IS NULL;

CREATE INDEX IF NOT EXISTS idx_notes_user_id_created_at
ON notes (user_id, created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS note_review_usage (
    note_id BIGINT NOT NULL REFERENCES notes (id) ON DELETE CASCADE,
    usage_date DATE NOT NULL,
    request_count INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (note_id, usage_date)
);

CREATE TABLE IF NOT EXISTS user_saved_sbar (
    user_id BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    selected_note_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    rows JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
    id BIGSERIAL PRIMARY KEY,
    note_id BIGINT NOT NULL REFERENCES notes (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    urgency TEXT NOT NULL DEFAULT 'baixa',
    recurrence_hours INTEGER NOT NULL DEFAULT 0,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tasks_user_id ON tasks (user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_note_id ON tasks (note_id);


CREATE TABLE IF NOT EXISTS locations (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_locations_user_id ON locations (user_id);

ALTER TABLE notes
ADD COLUMN IF NOT EXISTS location_id BIGINT REFERENCES locations (id) ON DELETE SET NULL;

ALTER TABLE notes
ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'ativo';

ALTER TABLE notes
ADD COLUMN IF NOT EXISTS is_favorite BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS evolutions (
    id BIGSERIAL PRIMARY KEY,
    note_id BIGINT NOT NULL REFERENCES notes (id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_evolutions_note_id ON evolutions (note_id);

CREATE TABLE IF NOT EXISTS quick_notes (
    user_id BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    content TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
